import { useCallback, useRef } from "react";
import type { Dispatch, MutableRefObject } from "react";
import type { RateLimitSnapshot, TurnPlan } from "@/types";
import { interruptTurn as interruptTurnService } from "@services/tauri";
import { getThreadTimestamp } from "@utils/threadItems";
import {
  asString,
  normalizePlanUpdate,
  normalizeRateLimits,
  normalizeTokenUsage,
} from "@threads/utils/threadNormalize";
import {
  getThreadDisplayTitle,
  looksAutoGeneratedThreadName,
} from "@threads/utils/threadNaming";
import {
  getLiveThreadSubagentSummaryPatch,
  getThreadStartAction,
  normalizeThreadStatusType,
  resetThreadTurnState,
  shouldClearCompletedPlanForThread,
  shouldIgnoreOrphanSubagentThread,
} from "./threadTurnEventHelpers";
import type { ThreadAction } from "./useThreadsReducer";

type UseThreadTurnEventsOptions = {
  dispatch: Dispatch<ThreadAction>;
  planByThreadRef: MutableRefObject<Record<string, TurnPlan | null>>;
  getCurrentRateLimits?: (workspaceId: string) => RateLimitSnapshot | null;
  getCustomName: (workspaceId: string, threadId: string) => string | undefined;
  isThreadHidden: (workspaceId: string, threadId: string) => boolean;
  setThreadLoaded: (threadId: string, isLoaded: boolean) => void;
  markProcessing: (threadId: string, isProcessing: boolean) => void;
  markReviewing: (threadId: string, isReviewing: boolean) => void;
  setActiveTurnId: (threadId: string, turnId: string | null) => void;
  getActiveTurnId: (threadId: string) => string | null;
  pendingInterruptsRef: MutableRefObject<Set<string>>;
  pushThreadErrorMessage: (
    threadId: string,
    message: string,
    options?: {
      itemType?: "stream-error" | "system-error";
      title?: string;
      detail?: string;
      status?: string;
    },
  ) => void;
  safeMessageActivity: () => void;
  recordThreadActivity: (workspaceId: string, threadId: string, timestamp?: number) => void;
};

export function useThreadTurnEvents({
  dispatch,
  planByThreadRef,
  getCurrentRateLimits,
  getCustomName,
  isThreadHidden,
  setThreadLoaded,
  markProcessing,
  markReviewing,
  setActiveTurnId,
  getActiveTurnId,
  pendingInterruptsRef,
  pushThreadErrorMessage,
  safeMessageActivity,
  recordThreadActivity,
}: UseThreadTurnEventsOptions) {
  const immediateActiveTurnIdByThreadRef = useRef<Record<string, string | null>>({});
  const lastReducerActiveTurnIdByThreadRef = useRef<Record<string, string | null>>({});
  const hasOptimisticActiveTurnByThreadRef = useRef<Record<string, boolean>>({});

  const getLatestKnownActiveTurnId = useCallback(
    (threadId: string) => {
      const reducerTurnId = getActiveTurnId(threadId);
      const lastReducerTurnId = lastReducerActiveTurnIdByThreadRef.current[threadId];
      const immediateTurnId = immediateActiveTurnIdByThreadRef.current[threadId];
      const hasOptimisticTurn =
        hasOptimisticActiveTurnByThreadRef.current[threadId] === true;

      if (hasOptimisticTurn && immediateTurnId !== undefined) {
        if (reducerTurnId === immediateTurnId) {
          // Reducer caught up with our optimistic write.
          hasOptimisticActiveTurnByThreadRef.current[threadId] = false;
        } else if (
          lastReducerTurnId !== undefined &&
          reducerTurnId !== lastReducerTurnId
        ) {
          // Reducer changed independently (e.g. resume hydration), so adopt it.
          hasOptimisticActiveTurnByThreadRef.current[threadId] = false;
          immediateActiveTurnIdByThreadRef.current[threadId] = reducerTurnId;
        } else {
          lastReducerActiveTurnIdByThreadRef.current[threadId] = reducerTurnId;
          return immediateTurnId;
        }
      }

      if (lastReducerTurnId !== reducerTurnId) {
        // Keep cache aligned with reducer when we are not in an optimistic window.
        lastReducerActiveTurnIdByThreadRef.current[threadId] = reducerTurnId;
        immediateActiveTurnIdByThreadRef.current[threadId] = reducerTurnId;
      }

      if (immediateTurnId !== undefined) {
        return immediateActiveTurnIdByThreadRef.current[threadId];
      }
      return reducerTurnId;
    },
    [getActiveTurnId],
  );

  const shouldClearCompletedPlan = useCallback(
    (threadId: string, turnId: string) =>
      shouldClearCompletedPlanForThread(planByThreadRef, threadId, turnId),
    [planByThreadRef],
  );

  const clearThreadRuntimeState = useCallback(
    (threadId: string, options?: { clearReviewing?: boolean }) => {
      markProcessing(threadId, false);
      if (options?.clearReviewing) {
        markReviewing(threadId, false);
      }
      resetThreadTurnState(
        {
          hasOptimisticActiveTurnByThreadRef,
          immediateActiveTurnIdByThreadRef,
          pendingInterruptsRef,
        },
        threadId,
      );
      setActiveTurnId(threadId, null);
    },
    [markProcessing, markReviewing, pendingInterruptsRef, setActiveTurnId],
  );

  const onThreadStarted = useCallback(
    (workspaceId: string, thread: Record<string, unknown>) => {
      const threadId = asString(thread.id);
      if (!threadId) {
        return;
      }
      const threadStartAction = getThreadStartAction(
        workspaceId,
        threadId,
        thread,
        isThreadHidden,
      );
      if (threadStartAction === "skip") {
        return;
      }
      if (threadStartAction === "hide") {
        dispatch({ type: "hideThread", workspaceId, threadId });
        return;
      }
      if (shouldIgnoreOrphanSubagentThread(thread)) {
        return;
      }
      const subagentSummaryPatch = getLiveThreadSubagentSummaryPatch(thread);
      dispatch({ type: "ensureThread", workspaceId, threadId });
      if (subagentSummaryPatch) {
        dispatch({
          type: "mergeThreadSummary",
          workspaceId,
          threadId,
          patch: subagentSummaryPatch,
        });
      }
      const timestamp = getThreadTimestamp(thread);
      const activityTimestamp = timestamp > 0 ? timestamp : Date.now();
      recordThreadActivity(workspaceId, threadId, activityTimestamp);
      dispatch({
        type: "setThreadTimestamp",
        workspaceId,
        threadId,
        timestamp: activityTimestamp,
      });

      const customName = getCustomName(workspaceId, threadId);
      if (!customName) {
        const preview = asString(thread.preview).trim();
        const name = getThreadDisplayTitle(thread, preview);
        if (name) {
          dispatch({ type: "setThreadName", workspaceId, threadId, name });
        }
      }
      safeMessageActivity();
    },
    [dispatch, getCustomName, isThreadHidden, recordThreadActivity, safeMessageActivity],
  );

  const onThreadNameUpdated = useCallback(
    (
      workspaceId: string,
      payload: { threadId: string; threadName: string | null },
    ) => {
      const { threadId, threadName } = payload;
      if (!threadId || !threadName) {
        return;
      }
      const normalizedThreadId = threadId.trim().toLowerCase();
      const normalizedThreadName = threadName.trim();
      if (
        normalizedThreadName.toLowerCase() === normalizedThreadId &&
        looksAutoGeneratedThreadName(normalizedThreadName)
      ) {
        return;
      }
      if (getCustomName(workspaceId, threadId)) {
        return;
      }
      dispatch({
        type: "setThreadName",
        workspaceId,
        threadId,
        name: normalizedThreadName,
      });
    },
    [dispatch, getCustomName],
  );

  const onThreadArchived = useCallback(
    (workspaceId: string, threadId: string) => {
      if (!threadId) {
        return;
      }
      dispatch({ type: "removeThread", workspaceId, threadId });
    },
    [dispatch],
  );

  const onThreadUnarchived = useCallback(
    (workspaceId: string, threadId: string) => {
      if (!threadId) {
        return;
      }
      dispatch({ type: "ensureThread", workspaceId, threadId });
      const customName = getCustomName(workspaceId, threadId);
      if (customName) {
        dispatch({
          type: "setThreadName",
          workspaceId,
          threadId,
          name: customName,
        });
      }
      const timestamp = Date.now();
      dispatch({
        type: "setThreadTimestamp",
        workspaceId,
        threadId,
        timestamp,
      });
      recordThreadActivity(workspaceId, threadId, timestamp);
      safeMessageActivity();
    },
    [dispatch, getCustomName, recordThreadActivity, safeMessageActivity],
  );

  const onTurnStarted = useCallback(
    (workspaceId: string, threadId: string, turnId: string) => {
      dispatch({
        type: "ensureThread",
        workspaceId,
        threadId,
      });
      if (pendingInterruptsRef.current.has(threadId)) {
        pendingInterruptsRef.current.delete(threadId);
        if (turnId) {
          void interruptTurnService(workspaceId, threadId, turnId).catch(() => {});
        }
        return;
      }
      markProcessing(threadId, true);
      if (turnId) {
        lastReducerActiveTurnIdByThreadRef.current[threadId] =
          getActiveTurnId(threadId);
        hasOptimisticActiveTurnByThreadRef.current[threadId] = true;
        immediateActiveTurnIdByThreadRef.current[threadId] = turnId;
        setActiveTurnId(threadId, turnId);
      }
    },
    [
      dispatch,
      getActiveTurnId,
      markProcessing,
      pendingInterruptsRef,
      setActiveTurnId,
    ],
  );

  const onTurnCompleted = useCallback(
    (_workspaceId: string, threadId: string, turnId: string) => {
      const activeTurnId = getLatestKnownActiveTurnId(threadId);
      if (turnId && activeTurnId && turnId !== activeTurnId) {
        return;
      }
      clearThreadRuntimeState(threadId);
      if (shouldClearCompletedPlan(threadId, turnId)) {
        dispatch({ type: "clearThreadPlan", threadId });
      }
    },
    [
      clearThreadRuntimeState,
      dispatch,
      getLatestKnownActiveTurnId,
      shouldClearCompletedPlan,
    ],
  );

  const onThreadStatusChanged = useCallback(
    (_workspaceId: string, threadId: string, status: Record<string, unknown>) => {
      const statusType = normalizeThreadStatusType(status);
      if (!statusType) {
        return;
      }
      if (statusType === "active") {
        markProcessing(threadId, true);
        return;
      }
      if (
        statusType === "idle" ||
        statusType === "notloaded" ||
        statusType === "systemerror"
      ) {
        clearThreadRuntimeState(threadId);
        if (statusType === "notloaded") {
          setThreadLoaded(threadId, false);
          markReviewing(threadId, false);
        }
      }
    },
    [
      clearThreadRuntimeState,
      markProcessing,
      markReviewing,
      setThreadLoaded,
    ],
  );

  const onThreadClosed = useCallback(
    (_workspaceId: string, threadId: string) => {
      setThreadLoaded(threadId, false);
      clearThreadRuntimeState(threadId, { clearReviewing: true });
    },
    [clearThreadRuntimeState, setThreadLoaded],
  );

  const onThreadRealtimeClosed = useCallback(
    (_workspaceId: string, threadId: string) => {
      clearThreadRuntimeState(threadId, { clearReviewing: true });
    },
    [clearThreadRuntimeState],
  );

  const onThreadStreamError = useCallback(
    (
      _workspaceId: string,
      threadId: string,
      message: string,
      options?: { willRetry?: boolean },
    ) => {
      if (!threadId || !message.trim()) {
        return;
      }
      if (!options?.willRetry) {
        clearThreadRuntimeState(threadId, { clearReviewing: true });
      }
      pushThreadErrorMessage(
        threadId,
        options?.willRetry ? `Stream error, retrying: ${message}` : `Stream error: ${message}`,
        {
          itemType: "stream-error",
          title: options?.willRetry ? "Stream error, retrying" : "Stream error",
          detail: "app-server",
          status: options?.willRetry ? "retrying" : "failed",
        },
      );
      safeMessageActivity();
    },
    [clearThreadRuntimeState, pushThreadErrorMessage, safeMessageActivity],
  );

  const onTurnPlanUpdated = useCallback(
    (
      workspaceId: string,
      threadId: string,
      turnId: string,
      payload: { explanation: unknown; plan: unknown },
    ) => {
      dispatch({ type: "ensureThread", workspaceId, threadId });
      const normalized = normalizePlanUpdate(
        turnId,
        payload.explanation,
        payload.plan,
      );
      dispatch({ type: "setThreadPlan", threadId, plan: normalized });
    },
    [dispatch],
  );

  const onTurnDiffUpdated = useCallback(
    (workspaceId: string, threadId: string, diff: string) => {
      dispatch({ type: "ensureThread", workspaceId, threadId });
      dispatch({ type: "setThreadTurnDiff", threadId, diff });
    },
    [dispatch],
  );

  const onThreadTokenUsageUpdated = useCallback(
    (
      workspaceId: string,
      threadId: string,
      tokenUsage: Record<string, unknown> | null,
    ) => {
      dispatch({ type: "ensureThread", workspaceId, threadId });
      dispatch({
        type: "setThreadTokenUsage",
        threadId,
        tokenUsage: normalizeTokenUsage(tokenUsage),
      });
    },
    [dispatch],
  );

  const onAccountRateLimitsUpdated = useCallback(
    (workspaceId: string, rateLimits: Record<string, unknown>) => {
      const previousRateLimits = getCurrentRateLimits?.(workspaceId) ?? null;
      dispatch({
        type: "setRateLimits",
        workspaceId,
        rateLimits: normalizeRateLimits(rateLimits, previousRateLimits),
      });
    },
    [dispatch, getCurrentRateLimits],
  );

  const onTurnError = useCallback(
    (
      workspaceId: string,
      threadId: string,
      turnId: string,
      payload: { message: string; willRetry: boolean },
    ) => {
      if (payload.willRetry) {
        const retryMessage = payload.message
          ? `Turn error, retrying: ${payload.message}`
          : "Turn error, retrying.";
        pushThreadErrorMessage(threadId, retryMessage, {
          itemType: "stream-error",
          title: "Turn error, retrying",
          detail: "app-server",
          status: "retrying",
        });
        safeMessageActivity();
        return;
      }
      const activeTurnId = getLatestKnownActiveTurnId(threadId);
      if (turnId && activeTurnId && turnId !== activeTurnId) {
        return;
      }
      dispatch({ type: "ensureThread", workspaceId, threadId });
      clearThreadRuntimeState(threadId, { clearReviewing: true });
      const message = payload.message
        ? `Turn failed: ${payload.message}`
        : "Turn failed.";
      pushThreadErrorMessage(threadId, message, {
        itemType: "stream-error",
        title: "Turn failed",
        detail: "app-server",
        status: "failed",
      });
      safeMessageActivity();
    },
    [
      clearThreadRuntimeState,
      dispatch,
      getLatestKnownActiveTurnId,
      pushThreadErrorMessage,
      safeMessageActivity,
    ],
  );

  return {
    onThreadStarted,
    onThreadNameUpdated,
    onThreadArchived,
    onThreadUnarchived,
    onTurnStarted,
    onTurnCompleted,
    onThreadStatusChanged,
    onThreadClosed,
    onThreadRealtimeClosed,
    onThreadStreamError,
    onTurnPlanUpdated,
    onTurnDiffUpdated,
    onThreadTokenUsageUpdated,
    onAccountRateLimitsUpdated,
    onTurnError,
  };
}
