import type { ConversationItem } from "@/types";
import { normalizeItem, prepareThreadItems, upsertItem } from "@utils/threadItems";
import type {
  StreamDeltaAction,
  ThreadAction,
  ThreadState,
} from "../useThreadsReducer";
import {
  addSummaryBoundary,
  dropLatestLocalReviewStart,
  ensureUniqueReviewId,
  extractRenameText,
  findMatchingReview,
  isDuplicateReviewById,
  looksAutoGeneratedThreadName,
  maybeRenameThreadFromAgent,
  mergeStreamingText,
  mergeStreamingToolOutput,
  prefersUpdatedSort,
} from "./common";

const preparedThreadItems = (state: ThreadState, items: ConversationItem[]) =>
  prepareThreadItems(items, { maxItemsPerThread: state.maxItemsPerThread });

const replaceThreadItem = (
  items: ConversationItem[],
  index: number,
  item: ConversationItem,
) => {
  const next = [...items];
  next[index] = item;
  return next;
};

type StreamDeltaBatchContext = {
  workingItemsByThread: Map<string, ConversationItem[]>;
  itemIndexByThread: Map<string, Map<string, number>>;
  changedThreadIds: Set<string>;
  threadNeedsPrepare: Set<string>;
  threadsByWorkspace: ThreadState["threadsByWorkspace"];
};

const getBatchThreadItems = (
  state: ThreadState,
  context: StreamDeltaBatchContext,
  threadId: string,
) => context.workingItemsByThread.get(threadId) ?? state.itemsByThread[threadId] ?? [];

const getWritableBatchThreadItems = (
  state: ThreadState,
  context: StreamDeltaBatchContext,
  threadId: string,
) => {
  const existing = context.workingItemsByThread.get(threadId);
  if (existing) {
    return existing;
  }
  const writable = [...(state.itemsByThread[threadId] ?? [])];
  context.workingItemsByThread.set(threadId, writable);
  return writable;
};

const getBatchItemIndex = (
  state: ThreadState,
  context: StreamDeltaBatchContext,
  threadId: string,
  itemId: string,
) => {
  let itemIndex = context.itemIndexByThread.get(threadId);
  if (!itemIndex) {
    itemIndex = new Map(
      getBatchThreadItems(state, context, threadId).map((item, index) => [
        item.id,
        index,
      ]),
    );
    context.itemIndexByThread.set(threadId, itemIndex);
  }
  return itemIndex.get(itemId) ?? -1;
};

const rememberBatchItemIndex = (
  context: StreamDeltaBatchContext,
  threadId: string,
  itemId: string,
  index: number,
) => {
  const itemIndex = context.itemIndexByThread.get(threadId);
  itemIndex?.set(itemId, index);
};

const applyStreamDeltaToBatch = (
  state: ThreadState,
  context: StreamDeltaBatchContext,
  action: StreamDeltaAction,
) => {
  switch (action.type) {
    case "appendAgentDelta": {
      const readableList = getBatchThreadItems(state, context, action.threadId);
      const index = getBatchItemIndex(
        state,
        context,
        action.threadId,
        action.itemId,
      );
      const writableList = getWritableBatchThreadItems(
        state,
        context,
        action.threadId,
      );
      if (index >= 0 && readableList[index].kind === "message") {
        const existing = writableList[index];
        if (existing.kind === "message") {
          writableList[index] = {
            ...existing,
            text: mergeStreamingText(existing.text, action.delta),
          };
        }
      } else {
        writableList.push({
          id: action.itemId,
          kind: "message",
          role: "assistant",
          text: action.delta,
        });
        rememberBatchItemIndex(
          context,
          action.threadId,
          action.itemId,
          writableList.length - 1,
        );
        context.threadNeedsPrepare.add(action.threadId);
      }
      context.changedThreadIds.add(action.threadId);
      context.threadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: writableList,
        itemId: action.itemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: context.threadsByWorkspace,
      });
      break;
    }
    case "appendReasoningSummary":
    case "appendReasoningContent": {
      const index = getBatchItemIndex(
        state,
        context,
        action.threadId,
        action.itemId,
      );
      const writableList = getWritableBatchThreadItems(
        state,
        context,
        action.threadId,
      );
      const base =
        index >= 0 && writableList[index].kind === "reasoning"
          ? (writableList[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const updated: ConversationItem =
        action.type === "appendReasoningSummary"
          ? ({
              ...base,
              summary: mergeStreamingText(
                "summary" in base ? base.summary : "",
                action.delta,
              ),
            } as ConversationItem)
          : ({
              ...base,
              content: mergeStreamingText(
                "content" in base ? base.content : "",
                action.delta,
              ),
            } as ConversationItem);
      if (index >= 0) {
        writableList[index] = updated;
      } else {
        writableList.push(updated);
        rememberBatchItemIndex(
          context,
          action.threadId,
          action.itemId,
          writableList.length - 1,
        );
        context.threadNeedsPrepare.add(action.threadId);
      }
      context.changedThreadIds.add(action.threadId);
      break;
    }
    case "appendPlanDelta": {
      const index = getBatchItemIndex(
        state,
        context,
        action.threadId,
        action.itemId,
      );
      const writableList = getWritableBatchThreadItems(
        state,
        context,
        action.threadId,
      );
      const base =
        index >= 0 && writableList[index].kind === "tool"
          ? writableList[index]
          : {
              id: action.itemId,
              kind: "tool",
              toolType: "plan",
              title: "Plan",
              detail: "",
              status: "in_progress",
              output: "",
            };
      const existingOutput = base.kind === "tool" ? (base.output ?? "") : "";
      const updated: ConversationItem = {
        ...(base as ConversationItem),
        kind: "tool",
        toolType: "plan",
        title: "Plan",
        detail: "Generating plan...",
        status: "in_progress",
        output: mergeStreamingText(existingOutput, action.delta),
      } as ConversationItem;
      if (index >= 0) {
        writableList[index] = updated;
      } else {
        writableList.push(updated);
        rememberBatchItemIndex(
          context,
          action.threadId,
          action.itemId,
          writableList.length - 1,
        );
        context.threadNeedsPrepare.add(action.threadId);
      }
      context.changedThreadIds.add(action.threadId);
      break;
    }
    case "appendToolOutput": {
      const readableList = getBatchThreadItems(state, context, action.threadId);
      const index = getBatchItemIndex(
        state,
        context,
        action.threadId,
        action.itemId,
      );
      if (index < 0 || readableList[index].kind !== "tool") {
        break;
      }
      const writableList = getWritableBatchThreadItems(
        state,
        context,
        action.threadId,
      );
      const existing = writableList[index];
      if (existing.kind === "tool") {
        writableList[index] = {
          ...existing,
          output: mergeStreamingToolOutput(existing.output ?? "", action.delta),
        } as ConversationItem;
        context.changedThreadIds.add(action.threadId);
      }
      break;
    }
  }
};

const reduceStreamDeltaBatch = (
  state: ThreadState,
  deltas: StreamDeltaAction[],
) => {
  const context: StreamDeltaBatchContext = {
    workingItemsByThread: new Map(),
    itemIndexByThread: new Map(),
    changedThreadIds: new Set(),
    threadNeedsPrepare: new Set(),
    threadsByWorkspace: state.threadsByWorkspace,
  };

  for (const delta of deltas) {
    applyStreamDeltaToBatch(state, context, delta);
  }

  if (
    context.changedThreadIds.size === 0 &&
    context.threadsByWorkspace === state.threadsByWorkspace
  ) {
    return state;
  }

  let nextItemsByThread = state.itemsByThread;
  for (const threadId of context.changedThreadIds) {
    const items = context.workingItemsByThread.get(threadId);
    if (!items) {
      continue;
    }
    const nextItems = context.threadNeedsPrepare.has(threadId)
      ? preparedThreadItems(state, items)
      : items;
    if (nextItemsByThread === state.itemsByThread) {
      nextItemsByThread = { ...state.itemsByThread };
    }
    nextItemsByThread[threadId] = nextItems;
  }

  return {
    ...state,
    itemsByThread: nextItemsByThread,
    threadsByWorkspace: context.threadsByWorkspace,
  };
};

export function reduceThreadItems(state: ThreadState, action: ThreadAction): ThreadState {
  switch (action.type) {
    case "appendStreamDeltasBatch":
      return reduceStreamDeltaBatch(state, action.deltas);
    case "addAssistantMessage": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const message: ConversationItem = {
        id: `${Date.now()}-assistant`,
        kind: "message",
        role: "assistant",
        text: action.text,
      };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: preparedThreadItems(state, [...list, message]),
        },
      };
    }
    case "addErrorItem": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const itemType = action.itemType ?? "stream-error";
      const title = action.title ?? (itemType === "system-error" ? "System error" : "Stream error");
      const detail = action.detail ?? "error";
      const message: ConversationItem = {
        id: `${Date.now()}-${list.length}-${itemType}`,
        kind: "tool",
        toolType: "error",
        itemType,
        title,
        detail,
        status: action.status ?? "failed",
        output: action.text,
      };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: preparedThreadItems(state, [...list, message]),
        },
      };
    }
    case "appendAgentDelta": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((msg) => msg.id === action.itemId);
      let updatedItems: ConversationItem[];
      if (index >= 0 && list[index].kind === "message") {
        const existing = list[index];
        updatedItems = replaceThreadItem(list, index, {
          ...existing,
          text: mergeStreamingText(existing.text, action.delta),
        });
      } else {
        updatedItems = preparedThreadItems(state, [
          ...list,
          {
            id: action.itemId,
            kind: "message",
            role: "assistant",
            text: action.delta,
          },
        ]);
      }
      const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: updatedItems,
        itemId: action.itemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: state.threadsByWorkspace,
      });
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "completeAgentMessage": {
      const list = [...(state.itemsByThread[action.threadId] ?? [])];
      const index = list.findIndex((msg) => msg.id === action.itemId);
      if (index >= 0 && list[index].kind === "message") {
        const existing = list[index];
        list[index] = {
          ...existing,
          text: action.text || existing.text,
        };
      } else {
        list.push({
          id: action.itemId,
          kind: "message",
          role: "assistant",
          text: action.text,
        });
      }
      const updatedItems = preparedThreadItems(state, list);
      const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: updatedItems,
        itemId: action.itemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: state.threadsByWorkspace,
      });
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "upsertItem": {
      let list = state.itemsByThread[action.threadId] ?? [];
      const item = normalizeItem(action.item);
      const isUserMessage = item.kind === "message" && item.role === "user";
      const hadUserMessage = isUserMessage
        ? list.some((entry) => entry.kind === "message" && entry.role === "user")
        : false;
      const renameText = isUserMessage ? extractRenameText(item.text) : "";
      if (
        item.kind === "review" &&
        item.state === "started" &&
        !item.id.startsWith("review-start-")
      ) {
        list = dropLatestLocalReviewStart(list);
      }
      if (item.kind === "review" && isDuplicateReviewById(list, item)) {
        return state;
      }
      if (item.kind === "review") {
        const existing = findMatchingReview(list, item);
        if (existing && existing.id !== item.id) {
          return state;
        }
      }
      const nextItem = ensureUniqueReviewId(list, item);
      const updatedItems = preparedThreadItems(state, upsertItem(list, nextItem));
      let nextThreadsByWorkspace = state.threadsByWorkspace;
      if (isUserMessage) {
        const threads = state.threadsByWorkspace[action.workspaceId] ?? [];
        const textValue = renameText;
        const updatedThreads = threads.map((thread) => {
          if (thread.id !== action.threadId) {
            return thread;
          }
          const looksAutoGenerated = looksAutoGeneratedThreadName(thread.name);
          const shouldRename =
            !hadUserMessage &&
            textValue.length > 0 &&
            looksAutoGenerated &&
            !action.hasCustomName;
          const nextName =
            shouldRename && textValue.length > 38
              ? `${textValue.slice(0, 38)}…`
              : shouldRename
                ? textValue
                : thread.name;
          return { ...thread, name: nextName };
        });
        const bumpedThreads =
          prefersUpdatedSort(state, action.workspaceId) && updatedThreads.length
            ? [
                ...updatedThreads.filter((thread) => thread.id === action.threadId),
                ...updatedThreads.filter((thread) => thread.id !== action.threadId),
              ]
            : updatedThreads;
        nextThreadsByWorkspace = {
          ...state.threadsByWorkspace,
          [action.workspaceId]: bumpedThreads,
        };
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "setThreadItems":
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(action.items, {
            maxItemsPerThread: action.preserveHistory ? null : state.maxItemsPerThread,
          }),
        },
      };
    case "appendReasoningSummary": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "reasoning"
          ? (list[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const updated: ConversationItem = {
        ...base,
        summary: mergeStreamingText(
          "summary" in base ? base.summary : "",
          action.delta,
        ),
      } as ConversationItem;
      const next =
        index >= 0
          ? replaceThreadItem(list, index, updated)
          : preparedThreadItems(state, [...list, updated]);
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: next,
        },
      };
    }
    case "appendReasoningSummaryBoundary": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "reasoning"
          ? (list[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const updated: ConversationItem = {
        ...base,
        summary: addSummaryBoundary("summary" in base ? base.summary : ""),
      } as ConversationItem;
      const next =
        index >= 0
          ? replaceThreadItem(list, index, updated)
          : preparedThreadItems(state, [...list, updated]);
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: next,
        },
      };
    }
    case "appendReasoningContent": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "reasoning"
          ? (list[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const updated: ConversationItem = {
        ...base,
        content: mergeStreamingText(
          "content" in base ? base.content : "",
          action.delta,
        ),
      } as ConversationItem;
      const next =
        index >= 0
          ? replaceThreadItem(list, index, updated)
          : preparedThreadItems(state, [...list, updated]);
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: next,
        },
      };
    }
    case "appendPlanDelta": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "tool"
          ? list[index]
          : {
              id: action.itemId,
              kind: "tool",
              toolType: "plan",
              title: "Plan",
              detail: "",
              status: "in_progress",
              output: "",
            };
      const existingOutput = base.kind === "tool" ? (base.output ?? "") : "";
      const updated: ConversationItem = {
        ...(base as ConversationItem),
        kind: "tool",
        toolType: "plan",
        title: "Plan",
        detail: "Generating plan...",
        status: "in_progress",
        output: mergeStreamingText(existingOutput, action.delta),
      } as ConversationItem;
      const next =
        index >= 0
          ? replaceThreadItem(list, index, updated)
          : preparedThreadItems(state, [...list, updated]);
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: next,
        },
      };
    }
    case "appendToolOutput": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      if (index < 0 || list[index].kind !== "tool") {
        return state;
      }
      const existing = list[index];
      const updated: ConversationItem = {
        ...existing,
        output: mergeStreamingToolOutput(existing.output ?? "", action.delta),
      } as ConversationItem;
      const next = replaceThreadItem(list, index, updated);
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: next,
        },
      };
    }
    default:
      return state;
  }
}
