const UUID_LIKE_THREAD_NAME_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const SHORT_HEX_THREAD_NAME_REGEX = /^[a-f0-9]{4,8}$/i;
const URL_REGEX = /https?:\/\/[^\s)）]+/i;
const MARKDOWN_IMAGE_REGEX = /!\[[^\]]*]\([^)]+\)/g;
const MARKDOWN_LINK_REGEX = /\[([^\]]+)]\([^)]+\)/g;
const CODE_FENCE_REGEX = /```[a-zA-Z0-9_-]*\n?|\n?```/g;
const SHELL_PROMPT_REGEX = /^\s*[$>]\s*/;
const LEADING_POLITE_REGEX =
  /^(帮我|请帮我|请|麻烦|麻烦帮我|帮忙|看下|看一下|查看一下|分析一下|修复一下|处理一下|帮我看下|帮我看一下)\s*/;
const LEADING_REFERENCE_REGEX = /^(这个|这里|当前|现在)\s*/;
const QUESTION_PREFIX_REGEX = /^(为什么|为啥|怎么|怎样|如何)\s*/;

const TITLE_MAX_LENGTH = 28;
const SERVER_TITLE_MAX_LENGTH = 38;

export function looksAutoGeneratedThreadName(name: string) {
  const trimmed = name.trim();
  return (
    trimmed === "New Agent" ||
    trimmed.startsWith("Agent ") ||
    SHORT_HEX_THREAD_NAME_REGEX.test(trimmed) ||
    UUID_LIKE_THREAD_NAME_REGEX.test(trimmed)
  );
}

export function clampThreadName(name: string, maxLength = 38): string | null {
  const trimmed = name.replace(/\s+/g, " ").trim();
  if (!trimmed) {
    return null;
  }
  return trimmed.length > maxLength
    ? `${trimmed.slice(0, maxLength)}…`
    : trimmed;
}

function normalizeTitleWhitespace(value: string) {
  return value.replace(/\s+/g, " ").trim();
}

function titleCaseToken(value: string) {
  if (!value) {
    return value;
  }
  return value[0].toUpperCase() + value.slice(1);
}

function getUrlTitle(value: string) {
  const match = value.match(URL_REGEX);
  if (!match) {
    return null;
  }
  try {
    const host = new URL(match[0]).hostname.replace(/^www\./, "");
    const brand = host.split(".")[0];
    return brand ? `查看 ${brand} 页面` : "查看网页";
  } catch {
    return "查看网页";
  }
}

function getCommandTitle(value: string) {
  const command = normalizeTitleWhitespace(value.replace(SHELL_PROMPT_REGEX, ""));
  const lower = command.toLowerCase();
  if (/^(npm|pnpm|yarn|bun)\s+install\b/.test(lower)) {
    return "安装依赖";
  }
  if (/^(npm|pnpm|yarn|bun)\s+run\s+typecheck\b/.test(lower)) {
    return "运行类型检查";
  }
  if (/^(npm|pnpm|yarn|bun)\s+run\s+test\b/.test(lower)) {
    return "运行测试";
  }
  if (/^(npm|pnpm|yarn|bun)\s+run\s+tauri:dev\b/.test(lower)) {
    return "运行 Tauri 开发服务";
  }
  const runMatch = command.match(/^(npm|pnpm|yarn|bun)\s+run\s+([^\s]+)/i);
  if (runMatch?.[2]) {
    return `运行 ${runMatch[2]}`;
  }
  if (/^(cargo|go|python|python3|node|deno|uv|git)\b/i.test(command)) {
    return `运行 ${command}`;
  }
  return null;
}

function stripTitleNoise(value: string) {
  let next = value
    .replace(CODE_FENCE_REGEX, " ")
    .replace(MARKDOWN_IMAGE_REGEX, " ")
    .replace(MARKDOWN_LINK_REGEX, "$1")
    .replace(/[`*_#>]/g, " ");
  next = normalizeTitleWhitespace(next);
  next = next.replace(LEADING_POLITE_REGEX, "");
  next = next.replace(LEADING_REFERENCE_REGEX, "");
  next = normalizeTitleWhitespace(next);
  return next;
}

function simplifyTitlePhrase(value: string) {
  return value
    .replace(/这个项目/g, "项目")
    .replace(/这个线程/g, "线程")
    .replace(/这里的/g, "")
    .replace(/当前的/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

export function deriveThreadDisplayTitle(preview: string, maxLength = TITLE_MAX_LENGTH) {
  const normalized = normalizeTitleWhitespace(preview);
  if (!normalized) {
    return null;
  }

  const withoutUrl = normalizeTitleWhitespace(normalized.replace(URL_REGEX, " "));
  const cleanedSource = stripTitleNoise(withoutUrl || normalized);
  const commandTitle = getCommandTitle(cleanedSource);
  if (commandTitle) {
    return clampThreadName(commandTitle, maxLength);
  }

  if (!withoutUrl || withoutUrl.length < 4) {
    return clampThreadName(getUrlTitle(normalized) ?? "查看网页", maxLength);
  }

  let title = simplifyTitlePhrase(
    cleanedSource.replace(/[。！？!?：:；;，,、]+$/g, ""),
  );
  if (!title) {
    return clampThreadName(getUrlTitle(normalized) ?? "查看网页", maxLength);
  }

  if (QUESTION_PREFIX_REGEX.test(title)) {
    title = `分析${simplifyTitlePhrase(title.replace(QUESTION_PREFIX_REGEX, ""))}原因`;
  }
  title = title.replace(/^我想要\s*/, "");
  title = title.replace(/^需要\s*/, "");
  title = normalizeTitleWhitespace(title);

  if (/^[a-z][a-z0-9_-]*$/i.test(title)) {
    title = titleCaseToken(title);
  }
  return clampThreadName(title, maxLength);
}

export function normalizeServerThreadTitle(title: unknown) {
  if (typeof title !== "string") {
    return null;
  }
  const normalized = normalizeTitleWhitespace(title);
  if (!normalized || looksAutoGeneratedThreadName(normalized)) {
    return null;
  }
  return clampThreadName(normalized, SERVER_TITLE_MAX_LENGTH);
}

export function getServerThreadTitle(thread: Record<string, unknown>) {
  return (
    normalizeServerThreadTitle(thread.threadName) ??
    normalizeServerThreadTitle(thread.thread_name) ??
    normalizeServerThreadTitle(thread.name) ??
    normalizeServerThreadTitle(thread.title)
  );
}

export function getThreadDisplayTitle(thread: Record<string, unknown>, preview: string) {
  return getServerThreadTitle(thread) ?? deriveThreadDisplayTitle(preview);
}
